services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MAVEN_OPTS=-Xmx1024m
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    volumes:
      - ./target:/workspace/target
      - ~/.m2:/root/.m2
    working_dir: /workspace
    command: mvn clean test -B -V

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - ./target/surefire-reports:/app/test-reports
