version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/static:/app/static:ro
    # 必要に応じて環境変数やボリュームを追加
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod
    # volumes:
    #   - ./logs:/app/logs
