name: Test Only

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # 毎日午前2時に実行

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run unit tests
      run: mvn test -B -V
      env:
        MAVEN_OPTS: -Xmx1024m
    
    - name: Run integration tests
      run: mvn verify -B -V
      env:
        MAVEN_OPTS: -Xmx1024m
    
    - name: Generate test coverage report
      run: mvn jacoco:report
    
    - name: Test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Test Results
        path: target/surefire-reports/*.xml
        reporter: java-junit
    
    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
